import "@/styles/globals.css";
import type { Metadata } from "next";
import AuthProvider from "@/providers/AuthProvider";
import { Inter } from "next/font/google";
import ContextProvider from "@/providers/ContextProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <AuthProvider>{children}</AuthProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
